name: HealthCheck

on:
  schedule:
    - cron: '* 17 * * *'

jobs:
  scheduled_healthcheck:
    runs-on: ubuntu-18.04 
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.5
      with:
        url: https://pokedex-55555.herokuapp.com/health